[package]
name = "mdt_dumper"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
# Zygisk-rs must be pulled from git
zygisk-rs = { git = "https://github.com/PerformanC/zygisk-rs.git" }
# Dobby-rs for hooking
dobby-rs = { git = "https://github.com/xm798/dobby-rs.git" }

# Standard Android logging & utilities
jni = "0.21"
log = "0.4"
android_logger = "0.13"
anyhow = "1.0"
nix = { version = "0.26", features = ["fs", "fcntl"] }
crc = "3.0"
hex = "0.4"
