[package]
name = "mdt_dumper"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
zygisk-rs = "0.4.0"  # Verify latest version
dobby-rs = "0.1"     # Needed for the hooking
jni = "0.21"
log = "0.4"
android_logger = "0.13"
anyhow = "1.0"
nix = { version = "0.26", features = ["fs", "fcntl"] }
crc = "3.0"
